#!/bin/sh

set -e
umask 0002

OPTIONS="--polar lock-on-removal --polar required --symlink-base /etc/pki/tls/certs --symlink-suffix .crt --symlink ca-certificate"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart authselect-autodiscovery.service
  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart sssd.service

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

