#!/bin/sh

set -e
umask 0002

OPTIONS="--polar with-faillock \
         --polar with-mkhomedir \
         --polar with-smartcard \
         --polar with-fingerprint \
         --polar with-pam-u2f \
         --polar with-pam-u2f-2fa \
         --polar without-pam-u2f-nouserok \
         --polar with-sudo \
         --lock /etc/device/system/auth/"

if [ "$1" == "--" ]; then

  /usr/libexec/device-tool ${OPTIONS} "$@"

  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart authselect-autodiscovery.service
  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart sssd.service

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-tool ${OPTIONS} "$@"

fi

