#!/bin/sh

set -e
umask 0002

OPTIONS="--show - --symlink-base=/usr/share/authselect/default --symlink-base=/usr/share/authselect/vendor --symlink-base=/etc/authselect/custom --symlink=profile"

if [ "$1" == "--" ]; then

  /usr/libexec/device-tool ${OPTIONS} "$@"

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-tool ${OPTIONS} "$@"

fi

