#!/bin/sh

set -e
umask 0002

if [ "$1" == "--" ]; then

  /usr/libexec/device-set --symlink-base=/usr/share/authselect/default --symlink-base=/usr/share/authselect/vendor --symlink-base=/etc/authselect/custom --symlink=profile "$@"

  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart authselect-autodiscovery.service

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set --symlink-base=/usr/share/authselect/default --symlink-base=/usr/share/authselect/vendor --symlink-base=/etc/authselect/custom --symlink=profile "$@"

fi

